-- =============================================================================
-- all-agents PostgreSQL schema
-- Modeled on the all-agents domain model (C:\Work\Projects\AI\all-agents).
--
-- Design rules applied (PostgreSQL best practices, database-skills references):
--   * BIGINT GENERATED ALWAYS AS IDENTITY for surrogate keys
--   * TIMESTAMPTZ everywhere (never TIMESTAMP without time zone)
--   * CHECK constraints instead of custom ENUM types (easier to evolve)
--   * Every FK column indexed (PostgreSQL does not index them automatically)
--   * Explicit ON DELETE CASCADE / SET NULL behavior
--   * Singular snake_case table names; {table}_{column}_idx / _check / _fkey
--   * created_at TIMESTAMPTZ NOT NULL DEFAULT now() on every table
--   * BRIN index on append-only time-ordered logs (agent_event)
--
-- Deliberate deviation: conversation.id, task.id and message ids are UUIDs
-- generated by the application (UUID.randomUUID()) and queried by that exact
-- value. A surrogate BIGINT would add a join on every access with no benefit,
-- so the application-owned UUID is kept as the natural primary key.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- presets: chat presets selectable per conversation (seeded from the app
-- configuration in all-agents/app/src/main/resources/application.yml)
-- ---------------------------------------------------------------------------
CREATE TABLE preset (
    id            TEXT PRIMARY KEY,                       -- config key: 'default', 'code-review', 'concise'
    name          TEXT NOT NULL,                          -- display name
    system_prompt TEXT,
    temperature   NUMERIC(3,2) NOT NULL DEFAULT 0.70,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT preset_temperature_check CHECK (temperature >= 0 AND temperature <= 2)
);

-- ---------------------------------------------------------------------------
-- agent: agent registry/catalog (AgentDefinition + A2A AgentCard).
-- The agent id is the name-based id used across the app ('master', pdf agent,
-- ...) and the natural key everything else references.
-- ---------------------------------------------------------------------------
CREATE TABLE agent (
    id                   TEXT PRIMARY KEY,
    name                 TEXT NOT NULL,                   -- display name
    description          TEXT,
    version              TEXT NOT NULL DEFAULT '0.0.1',
    url                  TEXT,                            -- A2A agent card URL
    streaming            BOOLEAN NOT NULL DEFAULT FALSE,  -- A2A capability
    push_notifications   BOOLEAN NOT NULL DEFAULT FALSE,  -- A2A capability
    default_input_modes  TEXT[] NOT NULL DEFAULT ARRAY['text']::TEXT[],
    default_output_modes TEXT[] NOT NULL DEFAULT ARRAY['text']::TEXT[],
    status               TEXT NOT NULL DEFAULT 'stopped', -- AgentStatus: STARTED | STOPPED
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(), -- bump on start/stop
    CONSTRAINT agent_status_check CHECK (status IN ('started', 'stopped'))
);

-- capabilities of an agent (AgentCapability: id + description)
CREATE TABLE agent_capability (
    agent_id      TEXT NOT NULL REFERENCES agent (id) ON DELETE CASCADE,
    capability_id TEXT NOT NULL,
    description   TEXT,
    PRIMARY KEY (agent_id, capability_id)
);

-- skills advertised by an agent on its A2A card (AgentSkill)
CREATE TABLE agent_skill (
    id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    agent_id    TEXT NOT NULL REFERENCES agent (id) ON DELETE CASCADE,
    skill_id    TEXT NOT NULL,
    name        TEXT NOT NULL,
    description TEXT,
    examples    TEXT[] NOT NULL DEFAULT '{}',
    CONSTRAINT agent_skill_agent_id_skill_id_key UNIQUE (agent_id, skill_id)
);

-- ---------------------------------------------------------------------------
-- tool: tool catalog (ToolInfo). Master agent searches tools by name.
-- ---------------------------------------------------------------------------
CREATE TABLE tool (
    id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL UNIQUE,
    description TEXT,
    owner       TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- tools available to an agent (AgentDefinition.toolNames)
CREATE TABLE agent_tool (
    agent_id TEXT NOT NULL REFERENCES agent (id) ON DELETE CASCADE,
    tool_id  BIGINT NOT NULL REFERENCES tool (id) ON DELETE CASCADE,
    PRIMARY KEY (agent_id, tool_id)
);

-- reverse lookup: which agents expose a given tool
CREATE INDEX agent_tool_tool_id_idx ON agent_tool (tool_id);

-- ---------------------------------------------------------------------------
-- conversation / message: chat history shown in the UI
-- ---------------------------------------------------------------------------
CREATE TABLE conversation (
    id         UUID PRIMARY KEY,                         -- UUID generated by the app
    title      TEXT NOT NULL,
    preset_id  TEXT REFERENCES preset (id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- list endpoint orders by created_at DESC
CREATE INDEX conversation_created_at_idx ON conversation (created_at);

CREATE TABLE message (
    id              BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    conversation_id UUID NOT NULL REFERENCES conversation (id) ON DELETE CASCADE,
    role            TEXT NOT NULL,
    content         TEXT NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT message_role_check CHECK (role IN ('user', 'assistant', 'system'))
);

-- hot path: SELECT ... FROM message WHERE conversation_id = ? ORDER BY id
CREATE INDEX message_conversation_id_id_idx ON message (conversation_id, id);

-- ---------------------------------------------------------------------------
-- chat_memory: Spring AI ChatMemory backing store (recent chat history sent
-- to the LLM). Same shape as the app's H2 schema.
-- ---------------------------------------------------------------------------
CREATE TABLE chat_memory (
    id              BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    conversation_id UUID NOT NULL REFERENCES conversation (id) ON DELETE CASCADE,
    role            TEXT NOT NULL,
    content         TEXT NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- Spring AI MessageType: user, assistant, system, tool
    CONSTRAINT chat_memory_role_check CHECK (role IN ('user', 'assistant', 'system', 'tool'))
);

-- same hot path: WHERE conversation_id = ? ORDER BY id
CREATE INDEX chat_memory_conversation_id_id_idx ON chat_memory (conversation_id, id);

-- ---------------------------------------------------------------------------
-- task: A2A (Agent2Agent) protocol task. The app is the A2A server here;
-- tasks are submitted to an agent and progress through state transitions.
-- ---------------------------------------------------------------------------
CREATE TABLE task (
    id            UUID PRIMARY KEY,                      -- UUID generated by the app
    context_id    TEXT,                                  -- conversation context; opaque string, may be empty
    agent_name    TEXT REFERENCES agent (id) ON DELETE SET NULL,
    state         TEXT NOT NULL,                         -- TaskState: submitted | working | completed | failed
    message_id    UUID,                                  -- AgentMessage.messageId
    message_role  TEXT,                                  -- 'agent' | 'user'
    message_parts JSONB NOT NULL DEFAULT '[]'::jsonb,    -- [{ "kind": "text", "text": "..." }, ...]
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),    -- bump on state transitions
    CONSTRAINT task_state_check CHECK (state IN ('submitted', 'working', 'completed', 'failed')),
    CONSTRAINT task_message_role_check CHECK (message_role IS NULL OR message_role IN ('user', 'agent'))
);

-- "tasks for this conversation" lookups
CREATE INDEX task_context_id_idx ON task (context_id);

-- ---------------------------------------------------------------------------
-- agent_request / agent_result: delegation requests and their results.
-- correlation_id links request -> events -> result and is the join key for
-- the future async (Kafka) mode.
-- ---------------------------------------------------------------------------
CREATE TABLE agent_request (
    id             BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    agent_id       TEXT REFERENCES agent (id) ON DELETE SET NULL,
    instruction    TEXT NOT NULL,
    payload        JSONB NOT NULL DEFAULT '{}'::jsonb,
    correlation_id TEXT,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX agent_request_correlation_id_idx ON agent_request (correlation_id);

CREATE TABLE agent_result (
    id         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    request_id BIGINT REFERENCES agent_request (id) ON DELETE SET NULL,
    agent_id   TEXT REFERENCES agent (id) ON DELETE SET NULL,
    content    TEXT NOT NULL,
    data       JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX agent_result_request_id_idx ON agent_result (request_id);

-- ---------------------------------------------------------------------------
-- agent_event: append-only event log (AgentEventBus).
-- AGENT_STARTED | AGENT_STOPPED | REQUEST_COMPLETED | REQUEST_FAILED
-- ---------------------------------------------------------------------------
CREATE TABLE agent_event (
    id             BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    event_type     TEXT NOT NULL,
    agent_name     TEXT NOT NULL,                        -- log survives agent deletion: no FK
    detail         TEXT,
    correlation_id TEXT,
    occurred_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT agent_event_event_type_check CHECK (
        event_type IN ('agent_started', 'agent_stopped', 'request_completed', 'request_failed'))
);

-- append-only time-ordered log: BRIN keeps the index tiny while rows are
-- inserted in timestamp order
CREATE INDEX agent_event_occurred_at_brin ON agent_event USING BRIN (occurred_at);
CREATE INDEX agent_event_correlation_id_idx ON agent_event (correlation_id);

-- ---------------------------------------------------------------------------
-- guardrail_check: audit log of guardrail decisions (GuardrailResult)
-- ---------------------------------------------------------------------------
CREATE TABLE guardrail_check (
    id             BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    guardrail_name TEXT NOT NULL,                        -- 'prompt-injection' | 'sensitive-data' | 'length' | ...
    allowed        BOOLEAN NOT NULL,
    content        TEXT,                                 -- possibly redacted content
    reason         TEXT,                                 -- block/redact reason, null when passed
    checked_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- "recent checks for guardrail X" — equality first, range/sort second
CREATE INDEX guardrail_check_name_checked_at_idx ON guardrail_check (guardrail_name, checked_at);

-- ---------------------------------------------------------------------------
-- Seed data: presets from all-agents application.yml
-- ---------------------------------------------------------------------------
INSERT INTO preset (id, name, system_prompt, temperature) VALUES
    ('default',     'Default',     NULL, 0.7),
    ('code-review', 'Code Review', 'You are a strict senior code reviewer. Review code critically and point out bugs, security issues and style problems.', 0.2),
    ('concise',     'Concise',     'Answer as briefly as possible, one or two sentences.', 0.3)
ON CONFLICT (id) DO NOTHING;
